export const seedData = [
  {
    name: 'Note 1',
    category: 'General',
    date: '2023-08-03',
    content: 'Content for Note 1',
    isArchived: false,
  },
  {
    name: 'Note 2',
    category: 'Work',
    date: '2023-08-04',
    content: 'Content for Note 2',
    isArchived: false,
  },
  {
    name: 'Note 3',
    category: 'General',
    date: '2023-08-05',
    content: 'Content for Note 3',
    isArchived: false,
  },
  {
    name: 'Note 4',
    category: 'Work',
    date: '2023-08-06',
    content: 'Content for Note 4',
    isArchived: false,
  },
  {
    name: 'Note 5',
    category: 'General',
    date: '2023-08-07',
    content: 'Content for Note 5',
    isArchived: false,
  },
  {
    name: 'Note 6',
    category: 'Work',
    date: '2023-08-08',
    content: 'Content for Note 6',
    isArchived: false,
  },
  {
    name: 'Note 7',
    category: 'General',
    date: '2023-08-09',
    content: 'Content for Note 7',
    isArchived: false,
  },
];
